version: "3"
services:
    php:
        build:
            context: docker/php
        working_dir: /code
        environment:
            APP_ENV: dev
            APP_DEBUG: "true"
        volumes:
            - ./:/code
